name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
    - type: checkboxes
        attributes:
          label: 同样的问题在上游是否也存在
          description: |
            在提问之前请先确定，同样的问题在  siyuan-note https://github.com/siyuan-note/siyuan 中是否也存在
          options:
            - label: |
                上游项目同样存在这个问题
              required: true
